name: Build, Publish and Release
run-name: ${{ github.actor }} is building, publishing and releasing 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  call-asset-build:
    if: github.event.pull_request.merged == true
    uses: luitjens-test-gh-app/workflows/.github/workflows/asset-build-and-publish.yml@3c6500b13df5a11342b49c5db30542d42846dac8
    secrets: inherit
